services:
  socialnetwork-service:
    container_name: socialnetwork-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - NEXT_PUBLIC_ACCESS_TOKEN_EXPIRY=604800000
      - NEXT_PUBLIC_ACCESS_REFRESH_EXPIRY=604800000
      - NEXT_PUBLIC_ACCESS_VERIFY_EXPIRY=900000